"""核心抽象层"""

from .base import AgentRole, AgentStatus, BaseAgent
from .cloud_utils import CLOUD_PREFIX, is_cloud_request, strip_cloud_prefix
from .config import (
    DEFAULT_AGENT_CLI_TIMEOUT,
    DEFAULT_ALLOWED_DOMAINS,
    DEFAULT_ALLOWED_URL_PREFIXES,
    DEFAULT_CLOUD_AUTH_TIMEOUT,
    DEFAULT_CLOUD_TIMEOUT,
    DEFAULT_COOLDOWN_AUTH,
    DEFAULT_COOLDOWN_AUTH_REQUIRE_CONFIG_CHANGE,
    DEFAULT_COOLDOWN_NETWORK,
    DEFAULT_COOLDOWN_RATE_LIMIT_DEFAULT,
    DEFAULT_COOLDOWN_RATE_LIMIT_MAX,
    DEFAULT_COOLDOWN_RATE_LIMIT_MIN,
    DEFAULT_COOLDOWN_TIMEOUT,
    DEFAULT_COOLDOWN_UNKNOWN,
    DEFAULT_EXECUTION_MODE,
    DEFAULT_EXTERNAL_LINK_ALLOWLIST,
    DEFAULT_EXTERNAL_LINK_MODE,
    DEFAULT_FETCH_POLICY_ALLOWED_DOMAINS,
    DEFAULT_FETCH_POLICY_ALLOWED_PATH_PREFIXES,
    DEFAULT_FETCH_POLICY_EXTERNAL_LINK_ALLOWLIST,
    DEFAULT_FETCH_POLICY_EXTERNAL_LINK_MODE,
    DEFAULT_MAX_ITERATIONS,
    DEFAULT_PLANNER_MODEL,
    DEFAULT_PLANNING_TIMEOUT,
    DEFAULT_REVIEW_TIMEOUT,
    DEFAULT_REVIEWER_MODEL,
    DEFAULT_URL_STRATEGY_ALLOWED_DOMAINS,
    DEFAULT_URL_STRATEGY_EXCLUDE_PATTERNS,
    DEFAULT_URL_STRATEGY_KEYWORD_BOOST_WEIGHT,
    DEFAULT_WORKER_MODEL,
    DEFAULT_WORKER_POOL_SIZE,
    DEFAULT_WORKER_TIMEOUT,
    MAX_CONSOLE_PREVIEW_CHARS,
    MAX_GOAL_SUMMARY_CHARS,
    MAX_KNOWLEDGE_DOC_PREVIEW_CHARS,
    TRUNCATION_HINT,
    TRUNCATION_HINT_OUTPUT,
    VALID_EXECUTION_MODES,
    VALID_EXTERNAL_LINK_MODES,
    CloudCooldownConfig,
    ConfigManager,
    DocsSourceConfig,
    OnlineFetchPolicyConfig,
    UnifiedOptions,
    build_cli_overrides_from_args,
    build_cooldown_config,
    build_unified_overrides,
    get_config,
    get_model_config,
    get_timeout_config,
)
from .execution_policy import (
    VIRTUAL_PROMPT_FOR_PREFIX_DETECTION,
    AmpersandPrefixInfo,
    AmpersandPrefixStatus,
    CloudFailureInfo,
    CloudFailureKind,
    DecisionInputs,
    EffectiveExecutionMode,
    ExecutionDecision,
    ExecutionModeResolution,
    ExecutionPolicyContext,
    SideEffectPolicy,
    build_execution_decision,
    build_user_facing_fallback_message,
    classify_cloud_failure,
    compute_decision_inputs,
    compute_side_effects,
    detect_ampersand_prefix,
    get_fallback_mode,
    is_cloud_mode,
    is_readonly_mode,
    resolve_effective_execution_mode,
    resolve_effective_execution_mode_full,
    sanitize_prompt_for_cli_fallback,
    should_route_ampersand_to_cloud,
    should_use_mp_orchestrator,
)
from .knowledge import (
    CURSOR_KEYWORDS,
    FALLBACK_CHARS_PER_DOC,
    MAX_CHARS_PER_DOC,
    MAX_CLI_ASK_CHARS_PER_DOC,
    MAX_CLI_ASK_DOCS,
    MAX_KNOWLEDGE_DOCS,
    MAX_TOTAL_KNOWLEDGE_CHARS,
    MIN_DOCS_ON_FALLBACK,
    KnowledgeDoc,
    is_cursor_related,
    truncate_knowledge_docs,
)
from .message import Message, MessageType
from .output_contract import (
    COOLDOWN_INFO_ALL_KNOWN_FIELDS,
    COOLDOWN_INFO_COMPAT_FIELDS,
    COOLDOWN_INFO_EXTENSION_FIELDS,
    COOLDOWN_INFO_MINIMUM_STABLE_FIELDS,
    COOLDOWN_INFO_REQUIRED_FIELDS,
    CloudResultFields,
    CooldownInfoFields,
    IterateResultFields,
    ResultFields,
    build_cloud_error_result,
    build_cloud_result,
    build_cloud_result_defaults,
    build_cloud_success_result,
    build_iterate_error_result,
    build_iterate_result_defaults,
    build_iterate_success_result,
)
from .state import AgentState, CommitContext, CommitPolicy, IterationState, IterationStatus, SystemState

__all__ = [
    # Agent 基础
    "AgentRole",
    "AgentStatus",
    "BaseAgent",
    # 消息
    "Message",
    "MessageType",
    # 状态
    "AgentState",
    "CommitContext",
    "CommitPolicy",
    "IterationState",
    "IterationStatus",
    "SystemState",
    # Cloud 工具
    "CLOUD_PREFIX",
    "is_cloud_request",
    "strip_cloud_prefix",
    # 知识库共享模块
    "CURSOR_KEYWORDS",
    "KnowledgeDoc",
    "is_cursor_related",
    "truncate_knowledge_docs",
    "MAX_KNOWLEDGE_DOCS",
    "MAX_CHARS_PER_DOC",
    "MAX_TOTAL_KNOWLEDGE_CHARS",
    "MAX_CLI_ASK_DOCS",
    "MAX_CLI_ASK_CHARS_PER_DOC",
    "FALLBACK_CHARS_PER_DOC",
    "MIN_DOCS_ON_FALLBACK",
    # 配置管理
    "DEFAULT_PLANNER_MODEL",
    "DEFAULT_WORKER_MODEL",
    "DEFAULT_REVIEWER_MODEL",
    "DEFAULT_PLANNING_TIMEOUT",
    "DEFAULT_WORKER_TIMEOUT",
    "DEFAULT_REVIEW_TIMEOUT",
    "DEFAULT_AGENT_CLI_TIMEOUT",
    "DEFAULT_CLOUD_TIMEOUT",
    "DEFAULT_CLOUD_AUTH_TIMEOUT",
    "DEFAULT_MAX_ITERATIONS",
    "DEFAULT_WORKER_POOL_SIZE",
    "DEFAULT_EXECUTION_MODE",
    # Cloud Cooldown 默认值
    "DEFAULT_COOLDOWN_RATE_LIMIT_MIN",
    "DEFAULT_COOLDOWN_RATE_LIMIT_DEFAULT",
    "DEFAULT_COOLDOWN_RATE_LIMIT_MAX",
    "DEFAULT_COOLDOWN_AUTH",
    "DEFAULT_COOLDOWN_AUTH_REQUIRE_CONFIG_CHANGE",
    "DEFAULT_COOLDOWN_NETWORK",
    "DEFAULT_COOLDOWN_TIMEOUT",
    "DEFAULT_COOLDOWN_UNKNOWN",
    # fetch_policy 默认值（在线抓取策略）
    "DEFAULT_FETCH_POLICY_ALLOWED_PATH_PREFIXES",
    "DEFAULT_FETCH_POLICY_ALLOWED_DOMAINS",
    "DEFAULT_FETCH_POLICY_EXTERNAL_LINK_MODE",
    "DEFAULT_FETCH_POLICY_EXTERNAL_LINK_ALLOWLIST",
    # url_strategy 默认值
    "DEFAULT_URL_STRATEGY_ALLOWED_DOMAINS",
    "DEFAULT_URL_STRATEGY_KEYWORD_BOOST_WEIGHT",
    "DEFAULT_URL_STRATEGY_EXCLUDE_PATTERNS",
    # 向后兼容别名
    "DEFAULT_ALLOWED_URL_PREFIXES",
    "DEFAULT_ALLOWED_DOMAINS",
    "DEFAULT_EXTERNAL_LINK_MODE",
    "DEFAULT_EXTERNAL_LINK_ALLOWLIST",
    # 控制台预览截断常量
    "MAX_CONSOLE_PREVIEW_CHARS",
    "MAX_KNOWLEDGE_DOC_PREVIEW_CHARS",
    "MAX_GOAL_SUMMARY_CHARS",
    "TRUNCATION_HINT",
    "TRUNCATION_HINT_OUTPUT",
    # 配置校验常量（向后兼容，规范定义见 knowledge.doc_url_strategy）
    "VALID_EXTERNAL_LINK_MODES",
    "VALID_EXECUTION_MODES",
    # 配置数据类
    "CloudCooldownConfig",
    "OnlineFetchPolicyConfig",
    "DocsSourceConfig",
    "ConfigManager",
    "get_config",
    "get_model_config",
    "get_timeout_config",
    # 配置构建函数
    "build_cooldown_config",
    # 统一 Overrides 构建 API
    "UnifiedOptions",
    "build_cli_overrides_from_args",
    "build_unified_overrides",
    # 执行策略
    "EffectiveExecutionMode",
    "CloudFailureKind",
    "AmpersandPrefixStatus",
    "CloudFailureInfo",
    "ExecutionModeResolution",
    "ExecutionPolicyContext",
    "ExecutionDecision",
    "AmpersandPrefixInfo",
    "SideEffectPolicy",
    "DecisionInputs",
    "VIRTUAL_PROMPT_FOR_PREFIX_DETECTION",
    "resolve_effective_execution_mode",
    "resolve_effective_execution_mode_full",
    "should_route_ampersand_to_cloud",
    "classify_cloud_failure",
    "build_user_facing_fallback_message",
    "sanitize_prompt_for_cli_fallback",
    "build_execution_decision",
    "detect_ampersand_prefix",
    "compute_side_effects",
    "compute_decision_inputs",
    "is_cloud_mode",
    "is_readonly_mode",
    "get_fallback_mode",
    "should_use_mp_orchestrator",
    # 输出契约 - 字段常量
    "ResultFields",
    "CloudResultFields",
    "IterateResultFields",
    # 输出契约 - CooldownInfoFields 及字段集合常量
    "CooldownInfoFields",
    "COOLDOWN_INFO_REQUIRED_FIELDS",
    "COOLDOWN_INFO_COMPAT_FIELDS",
    "COOLDOWN_INFO_MINIMUM_STABLE_FIELDS",
    "COOLDOWN_INFO_EXTENSION_FIELDS",
    "COOLDOWN_INFO_ALL_KNOWN_FIELDS",
    # 输出契约 - Cloud 结果构建器
    "build_cloud_result",
    "build_cloud_result_defaults",
    "build_cloud_error_result",
    "build_cloud_success_result",
    # 输出契约 - Iterate 结果构建器
    "build_iterate_result_defaults",
    "build_iterate_success_result",
    "build_iterate_error_result",
]
